#!/usr/bin/env node
var info = require('./package.json')
const fs = require("fs");
const { exec } = require('child_process');
var chalk = require('chalk')
var utils = require('./src/entry.js');

var arg1 = process.argv[2];
if (process.argv[2] == undefined) {
	console.log(chalk.red.bold("No args made"));
	process.exit()
} 
else if (arg1 == 'new') {
	utils.newTemplate()
}
else if (arg1 == 'test') {
	utils.test();
}
else if (arg1 == '--help' || arg1 == '-h') {
	console.log(chalk.white.bold("Structure:\n") + chalk.grey.bold("	nodenet <command> [args]\n") + chalk.white.bold("Commands:\n	new : Create a template for node like:[npm, console, ect.\n	test: Make a test for your node project using jest or chitchatjs\n        add/install : Installs npm package to your project. It cannot install global packages"))
}
else if (arg1 == '-v' || arg1 == '--version') {
  console.log(chalk.green.bold(`v${info.version}`));
}
else if (arg1 == 'add' || arg1 == "install") {
  utils.add();
}
else {
	console.log(chalk.red.bold("Unknown command."));
}