#!/usr/bin/env node
const fs = require("fs");
const { exec } = require('child_process');
var chalk = require('chalk')
var utils = require('./src/entry.js');

var arg1 = process.argv[2];
if (process.argv[2] == undefined) {
	console.log("No args made");
	process.exit()
} 
else if (arg1 == 'new') {
	utils.newTemplate()
}
else if (arg1 == 'test') {
	utils.test();
}